### ISSUE TITLE
如果使用GPU计算，速度提升到多少？

### ISSUE THREAD

**Issue by Hardold** [camel007/caffe_seetaFace_Identification#1]
你好，看到你写的代码，使用GPU加速之后，速度提升到多少？你改写之后相比于原seeta的identification，识别率会有下降吗？

**Comment by camel007** [comment]
1）提升是一定的，提升多少取决于你使用什么样的显卡
2）识别率没有任何改变，GPU提取的特征和作者源码提取的特征完全一致

**Comment by camel007** [comment]
1）提升是一定的，提升多少取决于你使用什么样的显卡
2）识别率没有任何改变，GPU提取的特征和作者源码提取的特征完全一致

**Comment by camel007** [comment]
1）提升是一定的，提升多少取决于你使用什么样的显卡
2）识别率没有任何改变，GPU提取的特征和作者源码提取的特征完全一致

**Comment by camel007** [comment]
1）提升是一定的，提升多少取决于你使用什么样的显卡
2）识别率没有任何改变，GPU提取的特征和作者源码提取的特征完全一致

**Comment by camel007** [comment]
1）提升是一定的，提升多少取决于你使用什么样的显卡
2）识别率没有任何改变，GPU提取的特征和作者源码提取的特征完全一致

**Comment by Hardold** [comment]
你现在的代码已经开发完成了？现在可以使用GPU计算吗？`
/*		#ifdef CPU_ONLY
		caffe::Caffe::set_mode(caffe::Caffe::CPU);
		#else
		  caffe::Caffe::set_mode(caffe::Caffe::GPU);
		#endif
		*/
		caffe::Caffe::set_mode(caffe::Caffe::CPU);`
看了这一段有些疑惑。我的电脑用作者源码的提取特征是140ms,GPU类型的NVIDIA  GeForce GTX 950 cuda 计算能力是5。这种GPU加速后速度能估计能达到多少？

**Comment by camel007** [comment]
I uncomment these code!
Please try again!  I do not have a 950 display card

**Comment by Hardold** [comment]
在你的电脑上，使用GPU计算的速度是多少？你的电脑的GPU型号是多少？Thanks!

**Comment by camel007** [comment]
I will update an test report later

**Comment by Hardold** [comment]
Thinks a lot,looking forward to your results.

**Comment by camel007** [comment]
average time consuming of 100 testing
CPU(i4790): 75ms
GPU(TITAN X): 0.25ms

**Comment by Hardold** [comment]
Thanks,This speed  is exciting,which increased by 300 times.Could you provide guidance on how to run this program? Thanks for your help !
